### ISSUE TITLE
Consider changing API to reflect repo name

### ISSUE THREAD

**Issue by adamnbowen** [arieh/ScrollBar#4]
I find it a _little_ strange that the API calls the class ScrollerBar, while the repo's name is ScrollBar.  I don't know if this will cause issues with the MooTools Forge (I haven't dealt with it before), but it would probably be best to have one name for everything, and "ScrollBar" seems best.

**Comment by arieh** [comment]
Technicaly you are right, but since the package cannot be removed from the forge, and that moving the repo/renaming it will also break it, there isn't much that can be done...

**Comment by adamnbowen** [comment]
I suspected as much... Oh well.
