### ISSUE TITLE
do not create a scrollbar if ratio < 1

### ISSUE THREAD

**Issue by adamnbowen** [arieh/ScrollBar#5]
Right now, whenever you call new Scrollbar, a scrollbar is always created, even if there is nothing to scroll (i.e., the content is not big enough to warrant a scrollbar).  This results in strange behavior when scrolled with the mousewheel (the interface breaks a bit).  I can see a couple of solutions to this:
- Create a scrollbar, but disable functionality (similar to setting overflow-y: scroll; on any html element)
- Do not create a scrollbar at all if the content is not long enough to warrant a scrollable scrollbar.

I'm unsure of the best way to do this, so I didn't push any changes up to my fork, but it is definitely something to think about.

**Comment by arieh** [comment]
I've implemented a fix, but not sure if it will work properly (don't have enough time to test). you can turn it off via options anyway

**Comment by adamnbowen** [comment]
okay, sounds good to me, I'll give it a test in a couple hours or so.

**Comment by adamnbowen** [comment]
I'm not sure how I feel about the `this.hide()` that you use, but it is workable.  However, the slider is still instantiated, so the div will scroll, even though there is no scrollbar.  I'll see if I can patch that.
